// Auto-generated by pipeline — Layout: split
export const businessData = {
  name: "Dhyana Dubai",
  category: "Yoga studio",
  address: "\nDhyana yoga and pilates Anantara, Business Tower - 26th floor) 2602 - 17th Street Marasi Dr - Business Bay - Dubai - United Arab Emirates",
  phone: "\n+971 56 137 0042",
  email: "",
  website: "https://dhyanadubai.com/",
  mapUrl: "https://www.google.com/maps/place/Dhyana+Dubai/data=!4m7!3m6!1s0x3e5f69d17bb65afd:0x2ebdca63443465!8m2!3d25.1856623!4d55.2637633!16s%2Fg%2F11cn931spk!19sChIJ_Vq2e9FpXz4RZTREY8q9LgA",
  latitude: "",
  longitude: "",
  rating: "",
  reviewsCount: "87",
  openingHours: "Show open hours for the week",
  images: ["https://lh3.googleusercontent.com/gps-cs-s/APNQkAEXaj8h7rpn8GEblrCPdRPpmrMzhCgshwruyjS4-_4Yi1vrwqLHs2Hp-nrwgGsxrJ2WAYJ-0vlUjiymvVux9_oer6aDP7O_FvO52T5Lfg0ioUB0yOzNoBk8Ah3HR9tuQeh7CBnR=w466-h240-k-no", "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEXaj8h7rpn8GEblrCPdRPpmrMzhCgshwruyjS4-_4Yi1vrwqLHs2Hp-nrwgGsxrJ2WAYJ-0vlUjiymvVux9_oer6aDP7O_FvO52T5Lfg0ioUB0yOzNoBk8Ah3HR9tuQeh7CBnR=w578-h298-k-no", "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEFKX6jeAIHUnGt5VZ8T2II_TVX_wVvoNEUYn9pJ1IoRm471QOfL1HDTWSP87nAHsRkIESls2E2OEzFMqoo_4wY-u6BrxUXRk3s4hP5Z2SK4dNkbmXoFknvBCo7IZ5IIwPhEkok=w541-h298-k-no", "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF9l7-VKEdS_Mt1T8clyGBeHF9IrfXmZpArEPpdqTlW4oD1ciLMYwmk9-GkHb3Vjtni5m7F46Cd2mSbvOge_Z9nHsqsl-tbG-sFCyjd6OKx4p1LQeKgTUHnOw6q2AU3Oer7bdxndw=w298-h298-k-no", "https://lh3.googleusercontent.com/a/ACg8ocLjA3nUZt_1YW1gfTeU2Qa3a9j_zQCnicHOnhnF2-UeTYMeHQ=w36-h36-p-rp-mo-br100", "https://lh3.googleusercontent.com/a-/ALV-UjWEn3-PICg0NNVK_qnJbBEK7srUhEq87sEI6YRbjINmLr4UP7A=w36-h36-p-rp-mo-br100", "https://lh3.googleusercontent.com/a-/ALV-UjWmB27kqIN-aSxgXL0MGwrSZxyH39MUQHE_YO0NcgWS2MTS4NGs=w36-h36-p-rp-mo-ba4-br100", "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGq9oHIf_l4Um90hVEq9as42D6ww49hjcctcDBq0X04aFN9zcMLzfC_Q2qAWj3czfxJedwVTx2f6Xifn0zvow9i5EAol_qhuwU7fIahVUJv_0wc1OiV5VZB74lm17tkXb-4rQZm6QMmUiDp=w156-h114-p-k-no"],
  description: "",
}

export const aiContent = {
  tagline: "Transform Body Soul",
  heroDescription: "Elevate your practice with breathtaking views of Dubai's skyline at Dhyana Dubai, a serene oasis offering expertly guided yoga and reformer pilates classes. Our experienced instructors will help you find balance and harmony in the heart of Business Bay. Let your journey to wellness begin with us.",
  aboutTitle: "Our Story: Where Movement Meets Mindfulness",
  aboutText: "Dhyana Dubai is more than just a yoga studio - it's a community of like-minded individuals seeking to enhance their physical, mental, and emotional well-being. Our state-of-the-art facilities and expert instructors provide a supportive environment for students of all levels to explore the transformative power of yoga and pilates. With a focus on small class sizes and personalized attention, we help our students cultivate a deeper connection with their bodies and minds. By combining innovative teaching methods with traditional practices, we empower our community to thrive in all aspects of life.",
  services: [
    { icon: "🧘", title: "Hatha Yoga", description: "Explore the traditional Indian practice of Hatha Yoga, focusing on physical postures and breathing techniques to balance the body's energy." },
    { icon: "🔥", title: "Hot Yoga", description: "Challenge yourself in our heated studio, where the intense heat detoxifies and strengthens the body, mind, and spirit." },
    { icon: "🌱", title: "Yin Yoga", description: "Experience the meditative and therapeutic benefits of Yin Yoga, targeting the deeper tissues of the body to promote flexibility and inner peace." },
    { icon: "🏋️‍♀️", title: "Reformer Pilates", description: "Engage your core and improve your overall physical fitness with our Reformer Pilates classes, using specialized equipment to enhance strength, flexibility, and body control." },
    { icon: "🌈", title: "Restorative Yoga", description: "Relax and rejuvenate with our Restorative Yoga classes, using props and gentle stretches to calm the mind and nourish the body." },
    { icon: "🕉️", title: "Meditation and Pranayama", description: "Cultivate inner peace and awareness through our guided meditation and pranayama sessions, exploring the ancient practices of breathwork and mindfulness." }
  ],
  whyChooseUs: [
    { icon: "🏙️", title: "Prime Location", description: "Conveniently located in the heart of Business Bay, our studio offers stunning views of the Dubai skyline and easy access to major transportation hubs." },
    { icon: "👥", title: "Experienced Instructors", description: "Our team of certified yoga and pilates instructors have years of experience teaching students of all levels, providing personalized attention and expert guidance." },
    { icon: "🌟", title: "State-of-the-Art Facilities", description: "Our modern and spacious studio is equipped with top-quality equipment and amenities, ensuring a comfortable and inspiring practice environment." },
    { icon: "📚", title: "Holistic Approach", description: "We offer a comprehensive range of classes and workshops that cater to the physical, mental, and emotional aspects of wellness, promoting a balanced and healthy lifestyle." }
  ],
  testimonials: [
    { name: "Aisha Al-Mansoori", role: "Local Business Owner", text: "I've been practicing yoga at Dhyana Dubai for a year now, and I've noticed a significant improvement in my flexibility and stress levels. The Hatha Yoga classes with instructor Fatima are my favorite - she's always pushing me to new heights!", rating: 5 },
    { name: "Rashid Hassan", role: "Fitness Enthusiast", text: "I was skeptical about trying Reformer Pilates, but the classes at Dhyana Dubai have been a game-changer for my core strength and overall fitness. The instructors are knowledgeable and supportive, and the studio has a great vibe.", rating: 5 },
    { name: "Leila Patel", role: "Busy Professional", text: "As a working mom, it's hard to find time for myself, but the Restorative Yoga classes at Dhyana Dubai have been a lifesaver. The studio is peaceful and calming, and the instructors are always willing to accommodate my schedule.", rating: 5 }
  ],
  ctaTitle: "Start Your Wellness Journey Today",
  ctaDescription: "Take the first step towards a healthier, happier you - sign up for a class or workshop at Dhyana Dubai and experience the transformative power of yoga and pilates for yourself. Limited spots available, so don't wait!",
  ctaButtonText: "Book Your Class",
  metaDescription: "Yoga studio in Business Bay, Dubai",
}

export const siteConfig = {
  layout: "split",
}
