// Auto-generated by pipeline
export const businessData = {
  name: "Dhyana Dubai",
  category: "Yoga studio",
  address: "\nDhyana yoga and pilates Anantara, Business Tower - 26th floor) 2602 - 17th Street Marasi Dr - Business Bay - Dubai - United Arab Emirates",
  phone: "\n+971 56 137 0042",
  email: "",
  website: "https://dhyanadubai.com/",
  mapUrl: "https://www.google.com/maps/place/Dhyana+Dubai/data=!4m7!3m6!1s0x3e5f69d17bb65afd:0x2ebdca63443465!8m2!3d25.1856623!4d55.2637633!16s%2Fg%2F11cn931spk!19sChIJ_Vq2e9FpXz4RZTREY8q9LgA",
  latitude: "",
  longitude: "",
  rating: "",
  reviewsCount: "87",
  openingHours: "Show open hours for the week",
  images: ["https://lh3.googleusercontent.com/gps-cs-s/APNQkAEXaj8h7rpn8GEblrCPdRPpmrMzhCgshwruyjS4-_4Yi1vrwqLHs2Hp-nrwgGsxrJ2WAYJ-0vlUjiymvVux9_oer6aDP7O_FvO52T5Lfg0ioUB0yOzNoBk8Ah3HR9tuQeh7CBnR=w466-h240-k-no", "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEXaj8h7rpn8GEblrCPdRPpmrMzhCgshwruyjS4-_4Yi1vrwqLHs2Hp-nrwgGsxrJ2WAYJ-0vlUjiymvVux9_oer6aDP7O_FvO52T5Lfg0ioUB0yOzNoBk8Ah3HR9tuQeh7CBnR=w578-h298-k-no", "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEFKX6jeAIHUnGt5VZ8T2II_TVX_wVvoNEUYn9pJ1IoRm471QOfL1HDTWSP87nAHsRkIESls2E2OEzFMqoo_4wY-u6BrxUXRk3s4hP5Z2SK4dNkbmXoFknvBCo7IZ5IIwPhEkok=w541-h298-k-no", "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF9l7-VKEdS_Mt1T8clyGBeHF9IrfXmZpArEPpdqTlW4oD1ciLMYwmk9-GkHb3Vjtni5m7F46Cd2mSbvOge_Z9nHsqsl-tbG-sFCyjd6OKx4p1LQeKgTUHnOw6q2AU3Oer7bdxndw=w298-h298-k-no", "https://lh3.googleusercontent.com/a/ACg8ocLjA3nUZt_1YW1gfTeU2Qa3a9j_zQCnicHOnhnF2-UeTYMeHQ=w36-h36-p-rp-mo-br100", "https://lh3.googleusercontent.com/a-/ALV-UjWEn3-PICg0NNVK_qnJbBEK7srUhEq87sEI6YRbjINmLr4UP7A=w36-h36-p-rp-mo-br100", "https://lh3.googleusercontent.com/a-/ALV-UjWmB27kqIN-aSxgXL0MGwrSZxyH39MUQHE_YO0NcgWS2MTS4NGs=w36-h36-p-rp-mo-ba4-br100", "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGq9oHIf_l4Um90hVEq9as42D6ww49hjcctcDBq0X04aFN9zcMLzfC_Q2qAWj3czfxJedwVTx2f6Xifn0zvow9i5EAol_qhuwU7fIahVUJv_0wc1OiV5VZB74lm17tkXb-4rQZm6QMmUiDp=w156-h114-p-k-no"],
  description: "",
}

export const aiContent = {
  tagline: "Find Inner Peace",
  heroDescription: "Welcome to Dhyana Dubai, where yoga and pilates meet luxury. Our state-of-the-art studio offers a serene escape from the city's hustle and bustle. Experience transformation and rejuvenation with our expert instructors.",
  aboutTitle: "Our Story: Harmony in Motion",
  aboutText: "At Dhyana Dubai, we believe in the transformative power of yoga and pilates. Our team of experienced instructors is dedicated to helping you achieve balance, flexibility, and inner peace. With a focus on holistic wellness, we strive to create a supportive community that nurtures body, mind, and spirit. Our studio is designed to provide a peaceful oasis in the heart of Dubai.",
  services: [
    { icon: "🧘", title: "Hatha Yoga", description: "Traditional yoga practice for balance and harmony" },
    { icon: "🏋️‍♀️", title: "Pilates", description: "Low-impact exercise for core strength and flexibility" },
    { icon: "🙏", title: "Meditation", description: "Guided meditation sessions for mental clarity and relaxation" },
    { icon: "👥", title: "Workshops", description: "Specialized workshops for yoga, pilates, and wellness" },
    { icon: "💆‍♀️", title: "Private Sessions", description: "Personalized instruction for customized wellness goals" },
    { icon: "📅", title: "Corporate Packages", description: "Wellness programs for businesses and teams" }
  ],
  whyChooseUs: [
    { icon: "🏆", title: "Expert Instructors", description: "Our team of experienced instructors provides personalized attention and guidance" },
    { icon: "🌟", title: "State-of-the-Art Studio", description: "Our luxury studio offers a serene and comfortable environment for practice" },
    { icon: "👫", title: "Supportive Community", description: "Our community is dedicated to helping you achieve your wellness goals" },
    { icon: "📈", title: "Holistic Approach", description: "We focus on nurturing body, mind, and spirit for overall wellness" }
  ],
  testimonials: [
    { name: "Rahul Jain", role: "Regular Practitioner", text: "I've been practicing at Dhyana Dubai for months, and I've seen a significant improvement in my flexibility and balance. The instructors are knowledgeable and supportive.", rating: 5 },
    { name: "Priya Patel", role: "Beginner Yogi", text: "I was nervous about trying yoga, but the instructors at Dhyana Dubai made me feel welcome and comfortable. The studio is beautiful and peaceful.", rating: 5 },
    { name: "Karan Singh", role: "Pilates Enthusiast", text: "The pilates classes at Dhyana Dubai are challenging and fun. The instructors are experienced and provide personalized attention.", rating: 5 }
  ],
  ctaTitle: "Start Your Wellness Journey",
  ctaDescription: "Join our community today and experience the transformative power of yoga and pilates. Book your first class now and take the first step towards a healthier, happier you.",
  ctaButtonText: "Book Now",
  metaDescription: "Luxury yoga and pilates studio in Dubai",
}
